language: swift

#osx_image: xcode10.1
osx_image: xcode11.1
env:
  matrix:
    - TEST_SDK=iphonesimulator13.1 OS=13.1 NAME='iPhone 11 Pro'
    #- TEST_SDK=iphonesimulator13.2 OS=10.14.6 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project FileOperations.xcodeproj -scheme FileOperations -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

notifications:  
  email:  
    recipients:  
    - rintoandrews90@gmail.com  
    on_success: always  
    on_failure: always
