language: swift

osx_image: xcode10.1
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=13.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=13.1 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project FileOperations.xcodeproj -scheme FileOperations -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

notifications:  
  email:  
    recipients:  
    - rintoandrews90@gmail.com  
    on_success: always  
    on_failure: always
